### ISSUE TITLE
Publish latest source code

### ISSUE THREAD

**Issue by diimdeep** [Seeed-Studio/DSO_Nano#1]
Please publish latest source code.
There is LIB v3.53 APP v3.64 on forums, but I can't find source code anywhere.

https://forum.seeedstudio.com/t/dso-firmware-version-3-64/

**Comment by xloem** [comment]
From your forum link I found https://gitlab.com/dsonano/dso-firmware . Not newer but looks more legit, has real git history in it. Bootloader code also in that user.
